<<<<<<< HEAD

spring.application.name=smartwallet-backend
spring.datasource.url=jdbc:mysql://localhost:3306/smartwalletdb
spring.datasource.username=root
spring.datasource.password=Arya

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
=======
spring.application.name=demo
>>>>>>> 41c155e8af121033716232812b12b12d02ef4db2
